[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  YARN_IGNORE_ENGINES = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
